# Generated by Django 4.1.5 on 2023-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("GEL", "GEL"), ("EUR", "EUR")],
                default="GEL",
                max_length=3,
            ),
        ),
    ]
